webtalk_init -webtalk_dir D:/phD/Term3/VHDL/project/SPI_ADAR7251_VHDL/SPI_ADAR7251_VHDL.sim/sim_1/behav/xsim/xsim.dir/tb_SPI_ADAR7251_40bit_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jan 26 00:21:55 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "204c8208-2ccc-4cc1-98f8-1a7c00c8fca4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "464f84c648fe4d1e8fe0678d32f50fc6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2008 R2 or Windows 7" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2494 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6368_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2005465815 -regid "" -xml D:/phD/Term3/VHDL/project/SPI_ADAR7251_VHDL/SPI_ADAR7251_VHDL.sim/sim_1/behav/xsim/xsim.dir/tb_SPI_ADAR7251_40bit_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/phD/Term3/VHDL/project/SPI_ADAR7251_VHDL/SPI_ADAR7251_VHDL.sim/sim_1/behav/xsim/xsim.dir/tb_SPI_ADAR7251_40bit_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/phD/Term3/VHDL/project/SPI_ADAR7251_VHDL/SPI_ADAR7251_VHDL.sim/sim_1/behav/xsim/xsim.dir/tb_SPI_ADAR7251_40bit_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
