@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Jan 26 00:15:59 +0330 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_SPI_ADAR7251_40bit_behav -key {Behavioral:sim_1:Functional:tb_SPI_ADAR7251_40bit} -tclbatch tb_SPI_ADAR7251_40bit.tcl -view D:/phD/Term3/VHDL/project/SPI_ADAR7251_VHDL/tb_SPI_ADAR7251_40bit_behav.wcfg -log simulate.log"
call xsim  tb_SPI_ADAR7251_40bit_behav -key {Behavioral:sim_1:Functional:tb_SPI_ADAR7251_40bit} -tclbatch tb_SPI_ADAR7251_40bit.tcl -view D:/phD/Term3/VHDL/project/SPI_ADAR7251_VHDL/tb_SPI_ADAR7251_40bit_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
